### ISSUE TITLE
overflow: overlay doesn't work on firefox.

### ISSUE THREAD

**Issue by kevinptt0323** [noootown/NCTU_cowbei#1]
https://github.com/noootown/NCTU_cowbei/blob/master/main.css#L68 
`overlay` doesn't work on firefox. use `auto` instead.

**Comment by noootown** [comment]
Oh thanks :), I'll fix it. Thank's for your advice.

**Comment by noootown** [comment]
btw I know you actually LOL.

**Comment by kevinptt0323** [comment]
but i don't. sry 😢
